@TOKEN_OPERATOR=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2RlcmF0b3JidWRpIiwiaWF0IjoxNzU0OTIyMTcyLCJleHAiOjE3NTQ5MjMwNzJ9.P3skRvrnPJHbQ_d64mkAGbiEFMPadDZrDAkyzOfVUdQ

### login request to example server
POST http://localhost:8080/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "moderatorbudi",
  "password": "budi4567"
}


### get all workers
###
GET http://localhost:8080/api/users/drivers/available
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

###
GET http://localhost:8080/api/users/drivers
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

### get all routes
GET http://localhost:8080/api/routes
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

### GET Truck Avaliable to make delivery
GET http://localhost:8080/api/trucks/available
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

### CREATE DELIVERY
POST http://localhost:8080/api/delivery
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

{
  "truck_id": "541b8fe0-3e2b-4afc-9342-54a7863cd49c",
  "route_id": "d330ece3-00b9-4d38-a524-60ec2abdc747",
  "worker_id": "6cd18362-8d31-41bb-bd20-f6dd048424f3",
  "latitude": -6.200000,
  "longitude": 106.816666
}

### GET Avaliable to make delivery
GET http://localhost:8080/api/delivery/active
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

### get transit point
GET http://localhost:8080/api/transit-points
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}


###
POST http://localhost:8080/api/delivery/transit
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

{
"delivery_id": "d5d1dec9-ad42-4b08-a126-31eb6360f884",
"transit_point_id": 55
}

###
GET http://localhost:8080/api/delivery/transit
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

###
GET http://localhost:8080/api/delivery/transit/pending
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

### get all delivery ACTIVE
GET http://localhost:8080/api/delivery/active
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

###
GET http://localhost:8080/api/delivery/transit/79c332d8-f762-4a28-adf4-25facfb7f119
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

###
PATCH http://localhost:8080/api/delivery/transit/accept-or-reject
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

{
  "delivery_transit_id": "79c332d8-f762-4a28-adf4-25facfb7f119",
  "is_accepted": true,
  "reason": "gas aja mayan duid nihh"
}


### get all delivery ACTIVE
GET http://localhost:8080/api/delivery/detail/d5d1dec9-ad42-4b08-a126-31eb6360f884
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}


### get all history delivery
PATCH http://localhost:8080/api/delivery/finish/984f6f89-2f0f-462e-8b79-0e79f77ce14d
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}


### get all history delivery
GET http://localhost:8080/api/delivery/history
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

### get all history delivery
GET http://localhost:8080/api/delivery/history/816c3d51-e2a1-4c8d-a2b6-6ac124e021c8
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

### ACC TRANSIT




### DELETE DELIVERY
DELETE http://localhost:8080/api/delivery/f0ce657b-d1a7-4b73-96ea-095fd7f269c6
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}



### FINISHED CURENNT DELIVERY
PATCH http://localhost:8080/api/delivery/{}/finish
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}


