@TOKEN_OPERATOR=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2RlcmF0b3JidWRpIiwiaWF0IjoxNzUzNTk3ODgwLCJleHAiOjE3NTM1OTg3ODB9.IwnQHw3E2T-cK_oPIOX0Ki5IhOU1buCBhUQoX_jdaR8

### login request to example server
POST http://localhost:8080/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "moderatorbudi",
  "password": "budi4567"
}


### get all workers
###
GET http://localhost:8080/api/users/drivers/available
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

### get all routes
GET http://localhost:8080/api/routes
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

### GET Truck Avaliable to make delivery
GET http://localhost:8080/api/trucks/available
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

### CREATE DELIVERY
POST http://localhost:8080/api/delivery
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

{
  "truck_id": "b8677164-0e63-45a6-b86d-b7facf784632",
  "route_id": "f6210933-83e4-4f9d-a498-5b1c95ae3643",
  "worker_id": "816c3d51-e2a1-4c8d-a2b6-6ac124e021c8",
  "latitude": -6.200000,
  "longitude": 106.816666
}

### get all delivery ACTIVE
GET http://localhost:8080/api/delivery/active
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}


### get all delivery ACTIVE
GET http://localhost:8080/api/delivery/detail/984f6f89-2f0f-462e-8b79-0e79f77ce14d
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}

### ACC TRANSIT




### DELETE DELIVERY
DELETE http://localhost:8080/api/delivery/f0ce657b-d1a7-4b73-96ea-095fd7f269c6
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}



### FINISHED CURENNT DELIVERY
PATCH http://localhost:8080/api/delivery/{}/finish
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN_OPERATOR}}


