package com.koriebruh.be.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@Data
public class DeliveryAlertDTO {
    private String id;
    private String type;
    private String message;
    private Long createdAt;
    private String senderId;      // null = auto-generated by system
    private String senderUsername; // Driver username if sender exists
    private String deliveryId;
}
